INSERT INTO PLANET(ID, NAME, CLIMATE, TERRAIN) VALUES(3, 'PLANETA 3', 'CLIMATE 3', 'TERRAIN 3');
INSERT INTO PLANET(ID, NAME, CLIMATE, TERRAIN) VALUES(4, 'Yavin IV', 'temperate, tropical', 'jungle, rainforests');
