
CREATE CACHED TABLE PUBLIC.PLANET( 
    PLANET_ID   INTEGER NOT NULL, 
    PLANET_NAME VARCHAR(150) NOT NULL, 
    PLANET_CLIMATE VARCHAR(150) NOT NULL,
    PLANET_TERRAIN VARCHAR(150) NOT NULL
);
ALTER TABLE PUBLIC.PLANET ADD CONSTRAINT PUBLIC.CONSTRAINT_PLANET_ID PRIMARY KEY(PLANET_ID);

